checks:
    php: true
filter:
    excluded_paths:
        - tests/*
build:
    tests:
        override:
            -
                command: phpunit --coverage-clover=/tmp/airpromo.xml
                coverage:
                    file: /tmp/airpromo.xml
                    format: php-clover
