search:
  path: /search/origin/{origin}/destination/{destination}/departureDate/{departureDate}
  host: "{sourceId}.%base_domain%"
  defaults:
    _controller: GalmiAirwaysBundle:Default:search
  methods: GET
  requirements:
    origin: "[A-Z0-9]{3}"
    destination: "[A-Z0-9]{3}"
    departureDate: "\d{4}-\d{2}-\d{2}"
    sourceId: "airasia|lionairthai|nokair"