services:
#    galmi_airways.example:
#        class: Galmi\AirwaysBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    galmi_airways.handlers.downloader:
        class: Galmi\AirwaysBundle\Handlers\Downloader

    galmi_airways.parser.airasia:
        class: Galmi\AirwaysBundle\Handlers\Parsers\AirAsia
        arguments: [@galmi_airways.handlers.downloader, %galmi_airways.sources.airasia.uri%]

    galmi_airways.parser.nokair:
        class: Galmi\AirwaysBundle\Handlers\Parsers\NokAir
        arguments: [@galmi_airways.handlers.downloader, %galmi_airways.sources.nokair.uri%]

    galmi_airways.parser.lionairthai:
        class: Galmi\AirwaysBundle\Handlers\Parsers\LionAirThai
        arguments: [@galmi_airways.handlers.downloader, %galmi_airways.sources.lionairthai.uri%]
