services:
#    galmi_airways.example:
#        class: Galmi\AirwaysBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    galmi_airways.handlers.downloader:
        class: Galmi\AirwaysBundle\Handlers\Downloader

    galmi_airways.searcher:
        class: Galmi\AirwaysBundle\Handlers\Searcher

    galmi_airways.parser.airasia:
        class: Galmi\AirwaysBundle\Handlers\Parsers\AirAsia

    galmi_airways.parser.nokair:
        class: Galmi\AirwaysBundle\Handlers\Parsers\NokAir

    galmi_airways.parser.lionairthai:
        class: Galmi\AirwaysBundle\Handlers\Parsers\LionAirThai

    galmi_airways.parser.thaismile:
        class: Galmi\AirwaysBundle\Handlers\Parsers\ThaiSmile

    galmi_airways.source.airasia:
        class: Galmi\AirwaysBundle\Handlers\Sources\AirAsia
        arguments: [@galmi_airways.handlers.downloader, @galmi_airways.parser.airasia, %galmi_airways.sources.airasia%]
        tags:
            - {name: "galmi_airways.source"}

    galmi_airways.source.nokair:
        class: Galmi\AirwaysBundle\Handlers\Sources\NokAir
        arguments: [@galmi_airways.handlers.downloader, @galmi_airways.parser.nokair, %galmi_airways.sources.nokair%]
        tags:
            - {name: "galmi_airways.source"}

    galmi_airways.sources.lionairthai:
        class: Galmi\AirwaysBundle\Handlers\Sources\LionAirThai
        arguments: [@galmi_airways.handlers.downloader, @galmi_airways.parser.lionairthai, %galmi_airways.sources.lionairthai%]
        tags:
            - {name: "galmi_airways.source"}

    galmi_airways.sources.thaismile:
        class: Galmi\AirwaysBundle\Handlers\Sources\ThaiSmile
        arguments: [@galmi_airways.handlers.downloader, @galmi_airways.parser.thaismile, %galmi_airways.sources.thaismile%]
        tags:
            - {name: "galmi_airways.source"}

    galmi_airways.locale_listener:
        class: Galmi\AirwaysBundle\EventListener\LocaleListener
        arguments: ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }
